# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openaws_client
from openaws_client.models.schema_create import SchemaCreate  # noqa: E501
from openaws_client.rest import ApiException

class TestSchemaCreate(unittest.TestCase):
    """SchemaCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SchemaCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaCreate`
        """
        model = openaws_client.models.schema_create.SchemaCreate()  # noqa: E501
        if include_optional :
            return SchemaCreate(
                type = '', 
                data = openaws_client.models.data.Data()
            )
        else :
            return SchemaCreate(
                type = '',
                data = openaws_client.models.data.Data(),
        )
        """

    def testSchemaCreate(self):
        """Test SchemaCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
