# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openaws_client
from openaws_client.models.entity_version_read import EntityVersionRead  # noqa: E501
from openaws_client.rest import ApiException

class TestEntityVersionRead(unittest.TestCase):
    """EntityVersionRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EntityVersionRead
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityVersionRead`
        """
        model = openaws_client.models.entity_version_read.EntityVersionRead()  # noqa: E501
        if include_optional :
            return EntityVersionRead(
                id = 56, 
                uuid = '', 
                status = 2, 
                schema_name = '', 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_by_id = '', 
                is_soft_deleted = True, 
                is_hard_deleted = True
            )
        else :
            return EntityVersionRead(
                id = 56,
                uuid = '',
                status = 2,
                schema_name = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by_id = '',
                is_soft_deleted = True,
                is_hard_deleted = True,
        )
        """

    def testEntityVersionRead(self):
        """Test EntityVersionRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
