# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openaws_client
from openaws_client.api.proxies_api import ProxiesApi  # noqa: E501
from openaws_client.rest import ApiException


class TestProxiesApi(unittest.TestCase):
    """ProxiesApi unit test stubs"""

    def setUp(self):
        self.api = openaws_client.api.proxies_api.ProxiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_records_get_record_v1_records_record_id_get(self):
        """Test case for records_get_record_v1_records_record_id_get

        Records:Get Record  # noqa: E501
        """
        pass

    def test_records_search_records_v1_records_get(self):
        """Test case for records_search_records_v1_records_get

        Records:Search Records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
