# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openaws_client
from openaws_client.models.body_verify_request_token_v1_auth_request_verify_token_post import BodyVerifyRequestTokenV1AuthRequestVerifyTokenPost  # noqa: E501
from openaws_client.rest import ApiException

class TestBodyVerifyRequestTokenV1AuthRequestVerifyTokenPost(unittest.TestCase):
    """BodyVerifyRequestTokenV1AuthRequestVerifyTokenPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyVerifyRequestTokenV1AuthRequestVerifyTokenPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyVerifyRequestTokenV1AuthRequestVerifyTokenPost`
        """
        model = openaws_client.models.body_verify_request_token_v1_auth_request_verify_token_post.BodyVerifyRequestTokenV1AuthRequestVerifyTokenPost()  # noqa: E501
        if include_optional :
            return BodyVerifyRequestTokenV1AuthRequestVerifyTokenPost(
                email = ''
            )
        else :
            return BodyVerifyRequestTokenV1AuthRequestVerifyTokenPost(
                email = '',
        )
        """

    def testBodyVerifyRequestTokenV1AuthRequestVerifyTokenPost(self):
        """Test BodyVerifyRequestTokenV1AuthRequestVerifyTokenPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
