# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openaws_client
from openaws_client.api.entities_api import EntitiesApi  # noqa: E501
from openaws_client.rest import ApiException


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self):
        self.api = openaws_client.api.entities_api.EntitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entity_create_entity_v1_entities_post(self):
        """Test case for entity_create_entity_v1_entities_post

        Entity:Create Entity  # noqa: E501
        """
        pass

    def test_entity_get_entities_v1_entities_get(self):
        """Test case for entity_get_entities_v1_entities_get

        Entity:Get Entities  # noqa: E501
        """
        pass

    def test_entity_get_entity_v1_entities_uuid_get(self):
        """Test case for entity_get_entity_v1_entities_uuid_get

        Entity:Get Entity  # noqa: E501
        """
        pass

    def test_entity_get_entity_version_v1_entities_uuid_versions_id_get(self):
        """Test case for entity_get_entity_version_v1_entities_uuid_versions_id_get

        Entity:Get Entity Version  # noqa: E501
        """
        pass

    def test_entity_get_entity_versions_v1_entities_uuid_versions_get(self):
        """Test case for entity_get_entity_versions_v1_entities_uuid_versions_get

        Entity:Get Entity Versions  # noqa: E501
        """
        pass

    def test_entity_hard_delete_entity_v1_entities_uuid_hard_delete(self):
        """Test case for entity_hard_delete_entity_v1_entities_uuid_hard_delete

        Entity:Hard Delete Entity  # noqa: E501
        """
        pass

    def test_entity_hard_delete_entity_version_v1_entities_uuid_versions_id_delete(self):
        """Test case for entity_hard_delete_entity_version_v1_entities_uuid_versions_id_delete

        Entity:Hard Delete Entity Version  # noqa: E501
        """
        pass

    def test_entity_restore_entity_from_soft_deletion_v1_entities_uuid_restore_patch(self):
        """Test case for entity_restore_entity_from_soft_deletion_v1_entities_uuid_restore_patch

        Entity:Restore Entity From Soft Deletion  # noqa: E501
        """
        pass

    def test_entity_rollback_to_a_previous_entity_version_v1_entities_uuid_versions_id_rollback_put(self):
        """Test case for entity_rollback_to_a_previous_entity_version_v1_entities_uuid_versions_id_rollback_put

        Entity:Rollback To A Previous Entity Version  # noqa: E501
        """
        pass

    def test_entity_soft_delete_entity_v1_entities_uuid_soft_delete(self):
        """Test case for entity_soft_delete_entity_v1_entities_uuid_soft_delete

        Entity:Soft Delete Entity  # noqa: E501
        """
        pass

    def test_entity_update_entity_v1_entities_uuid_patch(self):
        """Test case for entity_update_entity_v1_entities_uuid_patch

        Entity:Update Entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
