# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openaws_client
from openaws_client.models.user_create import UserCreate  # noqa: E501
from openaws_client.rest import ApiException

class TestUserCreate(unittest.TestCase):
    """UserCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserCreate`
        """
        model = openaws_client.models.user_create.UserCreate()  # noqa: E501
        if include_optional :
            return UserCreate(
                email = '', 
                password = '', 
                is_active = True, 
                is_superuser = True, 
                is_verified = True, 
                data = openaws_client.models.data.Data(), 
                permissions = openaws_client.models.user_permissions.UserPermissions(
                    guest = True, 
                    basic = True, 
                    employee = True, 
                    admin = True, ), 
                flags = 2
            )
        else :
            return UserCreate(
                email = '',
                password = '',
        )
        """

    def testUserCreate(self):
        """Test UserCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
