# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openaws_client
from openaws_client.models.user_update_permissions import UserUpdatePermissions  # noqa: E501
from openaws_client.rest import ApiException

class TestUserUpdatePermissions(unittest.TestCase):
    """UserUpdatePermissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserUpdatePermissions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUpdatePermissions`
        """
        model = openaws_client.models.user_update_permissions.UserUpdatePermissions()  # noqa: E501
        if include_optional :
            return UserUpdatePermissions(
                permissions = openaws_client.models.user_permissions.UserPermissions(
                    guest = True, 
                    basic = True, 
                    employee = True, 
                    admin = True, )
            )
        else :
            return UserUpdatePermissions(
                permissions = openaws_client.models.user_permissions.UserPermissions(
                    guest = True, 
                    basic = True, 
                    employee = True, 
                    admin = True, ),
        )
        """

    def testUserUpdatePermissions(self):
        """Test UserUpdatePermissions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
