# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openaws_client
from openaws_client.models.user_flag import UserFlag  # noqa: E501
from openaws_client.rest import ApiException

class TestUserFlag(unittest.TestCase):
    """UserFlag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserFlag(self):
        """Test UserFlag"""
        # inst = UserFlag()

if __name__ == '__main__':
    unittest.main()
