# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openaws_client
from openaws_client.api.users_api import UsersApi  # noqa: E501
from openaws_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = openaws_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_current_user_v1_users_me_get(self):
        """Test case for users_current_user_v1_users_me_get

        Users:Current User  # noqa: E501
        """
        pass

    def test_users_list_users_v1_users_get(self):
        """Test case for users_list_users_v1_users_get

        Users:List Users  # noqa: E501
        """
        pass

    def test_users_patch_current_user_v1_users_me_patch(self):
        """Test case for users_patch_current_user_v1_users_me_patch

        Users:Patch Current User  # noqa: E501
        """
        pass

    def test_users_patch_user_permissions_v1_users_id_permissions_patch(self):
        """Test case for users_patch_user_permissions_v1_users_id_permissions_patch

        Users:Patch User Permissions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
