# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openaws_client
from openaws_client.api.schemas_api import SchemasApi  # noqa: E501
from openaws_client.rest import ApiException


class TestSchemasApi(unittest.TestCase):
    """SchemasApi unit test stubs"""

    def setUp(self):
        self.api = openaws_client.api.schemas_api.SchemasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entity_create_schema_v1_schemas_post(self):
        """Test case for entity_create_schema_v1_schemas_post

        Entity:Create Schema  # noqa: E501
        """
        pass

    def test_entity_get_available_schemas_v1_schemas_get(self):
        """Test case for entity_get_available_schemas_v1_schemas_get

        Entity:Get Available Schemas  # noqa: E501
        """
        pass

    def test_entity_get_schema_v1_schemas_name_get(self):
        """Test case for entity_get_schema_v1_schemas_name_get

        Entity:Get Schema  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
