# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openaws_client
from openaws_client.api.auth_api import AuthApi  # noqa: E501
from openaws_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = openaws_client.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_db_bearer_login_v1_auth_jwt_login_post(self):
        """Test case for auth_db_bearer_login_v1_auth_jwt_login_post

        Auth:Db Bearer.Login  # noqa: E501
        """
        pass

    def test_auth_db_bearer_logout_v1_auth_jwt_logout_post(self):
        """Test case for auth_db_bearer_logout_v1_auth_jwt_logout_post

        Auth:Db Bearer.Logout  # noqa: E501
        """
        pass

    def test_auth_db_cookie_login_v1_auth_login_post(self):
        """Test case for auth_db_cookie_login_v1_auth_login_post

        Auth:Db Cookie.Login  # noqa: E501
        """
        pass

    def test_auth_db_cookie_logout_v1_auth_logout_post(self):
        """Test case for auth_db_cookie_logout_v1_auth_logout_post

        Auth:Db Cookie.Logout  # noqa: E501
        """
        pass

    def test_register_register_v1_auth_register_post(self):
        """Test case for register_register_v1_auth_register_post

        Register:Register  # noqa: E501
        """
        pass

    def test_reset_forgot_password_v1_auth_forgot_password_post(self):
        """Test case for reset_forgot_password_v1_auth_forgot_password_post

        Reset:Forgot Password  # noqa: E501
        """
        pass

    def test_reset_reset_password_v1_auth_reset_password_post(self):
        """Test case for reset_reset_password_v1_auth_reset_password_post

        Reset:Reset Password  # noqa: E501
        """
        pass

    def test_verify_request_token_v1_auth_request_verify_token_post(self):
        """Test case for verify_request_token_v1_auth_request_verify_token_post

        Verify:Request-Token  # noqa: E501
        """
        pass

    def test_verify_verify_v1_auth_verify_post(self):
        """Test case for verify_verify_v1_auth_verify_post

        Verify:Verify  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
