# coding: utf-8

"""
    Stadsarkivet

    API for Stadsarkivet  # noqa: E501

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openaws_client
from openaws_client.models.status_flag import StatusFlag  # noqa: E501
from openaws_client.rest import ApiException

class TestStatusFlag(unittest.TestCase):
    """StatusFlag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusFlag(self):
        """Test StatusFlag"""
        # inst = StatusFlag()

if __name__ == '__main__':
    unittest.main()
